Update 03/08/2021

diff --git a/Scripts/Automatisation-OpenFOAM/AllpostProcess b/Scripts/Automatisation-OpenFOAM/AllpostProcess
--- a/Scripts/Automatisation-OpenFOAM/AllpostProcess
+++ b/Scripts/Automatisation-OpenFOAM/AllpostProcess
@@ -2,12 +2,16 @@
 
 . ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions  #Charger les scripts OpenFOAM
 
+#* * * * * * * * * * * * * Fonctions * * * * * * * * * * * * * * * * * * * * * 
+
 usage() {
     echo "Utilisation : AllpostProcess [OPTIONS] <script1> <script2> ... <scriptN>"
     echo "  --log=<log_file> : définir un autre fichier log dans"
     echo "      lequel lire."
     echo "  -h, --help : afficher l'aide complète"
 }
+
+#------------------------------------------------------------------------------
 
 send_help() {
     echo
@@ -33,16 +37,35 @@ send_help() {
 
 }
 
+#------------------------------------------------------------------------------
+
+#Lancer une erreur avec un message et un code d'erreur 
+error() {
+	echo 
+	echo "--> Erreur : $@" 1>&2
+
+	#Si il n'y a qu'un seul argument : erreur 42
+	if [ $# -eq 1 ] ; then
+		exit 42
+	else
+		exit ${2}
+	fi
+}
+
+#------------------------------------------------------------------------------
+
 # Vérifier le code de sortie de $?. Si différent de 0, renvoie le code d'erreur $2
 # Donner le nom de l'application dans $1
 check_exit_code() {
 	if [ ! $? -eq 0 ]; then
-		echo "--> Erreur : ${1} a échoué."
+		error "${1} a échoué."
 		exit ${2}
 	else
 		echo "${1} terminé"
 	fi
 }
+
+#------------------------------------------------------------------------------
 
 execute_scripts() {
     #Pour chaque paramètre, l'exécuter
@@ -53,7 +76,8 @@ execute_scripts() {
     done
 }
 
-#==============================================================================
+
+#******************************************************************************
 
 LOGFILE="log.$(getApplication)" #Définir fichier log
 
@@ -98,8 +122,7 @@ for key in $@ ; do
             #Si le paramètre donné commence par un tiret, il n'est pas accepté
             if [ ! -z $(echo $key | grep -o "\-") ]; then
                 echo
-                echo "Erreur : argument invalide ${key}"
-                usage
+                error "Erreur : argument invalide ${key}" usage
                 exit 1
             fi
 		;;
@@ -109,31 +132,33 @@ done
 
 #Vérifier si il y a bien une liste d'arguments
 if [ $# -eq 0 ]; then
-    echo "Erreur : aucun script donné en paramètre"
+    error "Erreur : aucun script donné en paramètre"
     usage
     exit 1
 fi
 
-#==============================================================================
+#******************************************************************************
 
 #Lire le dernier temps de simulation
-TIME=$(tail -100 ${LOGFILE} | grep ^Time | tail -1 | grep -o "[0-9].*")
+TIME=$(tail -300 ${LOGFILE} | grep ^Time | tail -1 | grep -o "[0-9].*")
 check_exit_code "Lecture du fichier ${LOGFILE}" 2
 echo "Dernier temps dans le fichier ${LOGFILE} : ${TIME}"
 
 EMPTY_IF_END=$(tail ${LOGFILE} | grep "^End")
 
 #Boucler tant qu'on a pas terminé 
-while [ -z $EMPTY_IF_END ] && [ ! -z "${TIME}" ] ; do
+while [ -z $EMPTY_IF_RUNNING ] && [ ! -z "${TIME}" ] ; do
 
-    echo "Réexecution automatique dans 60 secondes"
-    sleep 60
+    sleep 2
+    clear
 
     #Lire le dernier temps de simulation
-    TIME=$(tail -100 ${LOGFILE} | grep ^Time | tail -1 | grep -o "[0-9].*") 
+    TIME=$(tail -300 ${LOGFILE} | grep ^Time | tail -1 | grep -Eo '[+-]?[0-9]+([.][0-9]+)?') 
+    dT=$(tail -300 ${LOGFILE} | grep ^deltaT | tail -1) 
     echo "Dernier temps dans le fichier ${LOGFILE}: ${TIME}"
+    echo "${dT}"
 
-    EMPTY_IF_END=$(tail ${LOGFILE} | grep "^End")
+    EMPTY_IF_RUNNING=$(tail ${LOGFILE} | grep "^End")
 
 done
 
